-- 017: chuyển mọi cột identity từ GENERATED ALWAYS → GENERATED BY DEFAULT.
--
-- Lý do: (1) seed tài khoản quỹ (boot DDL) insert id tường minh 1001-1003 → ALWAYS
-- chặn; (2) nạp dữ liệu data-only từ Supabase (COPY kèm cột id) cần chèn id tường
-- minh. DB Supabase cũ vốn cho phép (id chèn tay được) nên đây là bước hoà hợp.
-- An toàn: code app luôn INSERT không kèm id (để tự sinh) → BY DEFAULT vẫn tự sinh.
DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT table_name, column_name
    FROM information_schema.columns
    WHERE table_schema = 'public' AND identity_generation = 'ALWAYS'
  LOOP
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I SET GENERATED BY DEFAULT',
                   r.table_name, r.column_name);
  END LOOP;
END $$;
